# Generated by Django 5.1 on 2024-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('😃', 'Happy'), ('😐', 'Neutral'), ('😞', 'Sad'), ('😍', 'Love'), ('😡', 'Angry')], max_length=1)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
