# Generated by Django 5.1 on 2024-08-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_surveygroup_survey_survey_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='group',
        ),
        migrations.DeleteModel(
            name='SurveyGroup',
        ),
    ]
